#!/usr/bin/python3
import json
import urllib
import urllib.request
import getpass
import re
import sys
import platform

class bcolors:
    if platform.system() != "Windows":
        PURPLE = '\033[95m'
        BLUE = '\033[94m'
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        RED = '\033[91m'
        ENDC = '\033[0m'
        BOLD = '\033[1m'
        UNDERLINE = '\033[4m'
    else:
        PURPLE = ''
        BLUE = ''
        CYAN = ''
        GREEN = ''
        YELLOW = ''
        RED = ''
        ENDC = ''
        BOLD = ''
        UNDERLINE = ''

def connectToUrl(user, passwd):
    # create a password manager
    password_mgr = urllib.request.HTTPPasswordMgrWithDefaultRealm()

    # If we knew the realm, we could use it instead of None.
    top_level_url = "https://wis.fit.vutbr.cz/FIT/st"
    password_mgr.add_password(None, top_level_url, user, passwd)

    handler = urllib.request.HTTPBasicAuthHandler(password_mgr)

    # create "opener" (OpenerDirector instance)
    opener = urllib.request.build_opener(handler)

    #Check what semester is
    baseUrl = "https://wis.fit.vutbr.cz/FIT/st/get-coursesx.php?json=1&"
    semestrUrl = "sem=Z" if sys.argv[1]=="w" else "sem=L"
    baseUrl += semestrUrl

    # use the opener to fetch a URL
    try:
        opener.open(baseUrl)
    except:
        print(f"{bcolors.RED}Bad username || passord{bcolors.ENDC}")
        exit(1);

    # Install the opener.
    urllib.request.install_opener(opener)

    
    # Now all calls to urllib.request.urlopen use our opener.
    return urllib.request.urlopen(baseUrl)


def printData(data):
    for i in data:
        print(f'{bcolors.PURPLE}{i["abbrv"]}{bcolors.ENDC} ({i["title_e"]}):')
        try:
            grade = i["grade"].strip()
        except:
            grade = "Unknown"

        if grade != "4F" and grade != "Unknown":
            print(f'    Grade: {grade}') 
            print(f'    {bcolors.GREEN}[✔]You did it. Enjoy your well desired rest.{bcolors.ENDC}')
            continue;

        try: 
            color = bcolors.GREEN if i["credit_status"] == "yes" else bcolors.RED
            print(f'    {color}[💵]Credit: {i["credit_status"]}{bcolors.ENDC}')
        except:
            pass

        print(f'    Grade: {bcolors.RED}{grade}{bcolors.ENDC}') 

        for f in i["items"]:
            if re.match(r".*projekt.*", f["title"], re.IGNORECASE):
                if not re.match(r".*předchoz.*", f["title"], re.IGNORECASE):
                    print(f"    {bcolors.YELLOW}[!]Potencional requirement: {f['title']}{bcolors.ENDC}")

def loadUsername():
    try:
        with open("user", "r") as file:
            return file.readline().strip()
    except:
        return False

def saveUsername(username):
    with open("user", "w") as file:
        file.write(username)


def main():
    if len(sys.argv)<2:
        sys.exit("Usage: ./vutPtCheck (w || s - Semester switch")

    if not (user := loadUsername()):
        user = input("Username: ")
        switch = input("Do you want to save Username? y/n: ")
        if switch in ["y", "Y"]:
            saveUsername(user)

    passwd = getpass.getpass()

    r = connectToUrl(user, passwd)

    data = r.read()
    data = data.decode('utf-8')
    data = json.loads(data)
    data = data["data"]

    printData(data)

if __name__=="__main__":
    main()
